on:
  push:
    branches: ["**"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}   # pour avoir "Run workflow"

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest
    env:
      SONAR_HOST_URL: https://sonarcloud.io
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend
        working-directory: frontend
        run: |
          if [ -f package-lock.json ]; then
            echo "package-lock.json found, running npm ci"
            npm ci || (echo "npm ci failed, trying npm install instead" && npm install --no-audit --no-fund)
          else
            echo "No package-lock.json found, running npm install"
            npm install --no-audit --no-fund
          fi

      - name: Test Frontend (Vitest + coverage)
        working-directory: frontend
        run: npm run test:ci || echo "no frontend tests"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Backend
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Test Backend (pytest + coverage)
        working-directory: backend
        run: pytest --maxfail=1 --disable-warnings -q --cov=. --cov-report=xml:coverage.xml || echo "no backend tests"

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
